# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49347606ffc15694f8236bcf494ca89a9cf3d91b65205ffc62e96f7c46b0a1cd500daf284fce43f143ea55e02eb1170cb6a5c41a1ceada80bb6e8f531575738e

test:
  secret_key_base: 5a10bc34690f3fce8dc90be7bef97ed378a9f829a308173590820acbadf68d6e2113094d065cd339e61bc237617ffe066294e4494778007035c8e92a60febd51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
